# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ding < Formula
  desc "Stream-based alerting daemon — single binary, zero infrastructure"
  homepage "https://ding.ing"
  version "0.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ding-labs/ding/releases/download/v0.12.0/ding_darwin_amd64.tar.gz"
      sha256 "2cd68f7bfccd69547c993af16aa8cadbf8c5634ae2e0b6a23bb49cd46e3048c0"

      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ding-labs/ding/releases/download/v0.12.0/ding_darwin_arm64.tar.gz"
      sha256 "6822b1eb22693b2814166986a85608b8473583e00ae1b2adf13b7ac81dde89c9"

      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ding-labs/ding/releases/download/v0.12.0/ding_linux_amd64.tar.gz"
      sha256 "e8535a7053fc1020f9764e6492f90729ef8046f80df27fb6d20542894c5f6e97"
      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ding-labs/ding/releases/download/v0.12.0/ding_linux_arm64.tar.gz"
      sha256 "2e7d68e151a6339544d7ea9096c66fd9d0c46d68679f0eea08663b4a842d8a64"
      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  test do
    system "#{bin}/ding", "--version"
  end
end
