# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ding < Formula
  desc "Stream-based alerting daemon — single binary, zero infrastructure"
  homepage "https://ding.ing"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zuchka/ding/releases/download/v0.5.0/ding_darwin_amd64.tar.gz"
      sha256 "44f01794fed26768b3a98e9d04788ab7bb0e1e6a5e5817bc7d1a94d8981ee2f9"

      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zuchka/ding/releases/download/v0.5.0/ding_darwin_arm64.tar.gz"
      sha256 "3a04b9188552c3eaa32857ce54e63372507942a5a1e630ada0d2a931b5b4c1bf"

      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zuchka/ding/releases/download/v0.5.0/ding_linux_amd64.tar.gz"
      sha256 "6bf4262cccbd72ca6b84ba6f8843a5b6a483aa8862f1cea050b5eb90638c6664"
      define_method(:install) do
        bin.install "ding"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zuchka/ding/releases/download/v0.5.0/ding_linux_arm64.tar.gz"
      sha256 "46a50452563462e7262d2b364d69cf93099760dd01eaa47231e358cf27b0022f"
      define_method(:install) do
        bin.install "ding"
      end
    end
  end

  test do
    system "#{bin}/ding", "--version"
  end
end
